# REST Client extention in vscode (alternative to Postman)

### TEST GET /api/planets
GET http://localhost:8000/api/planets

### TEST GET /api/launches
GET http://localhost:8000/api/launches

### TEST POST /api/launches
POST http://localhost:8000/api/launches
content-type: application/json

{
    "mission": "test 1 mission",
    "rocket": "ZTM Experimental IS1",
    "target": "Kepler-62 f",
    "launchDate": "January 17, 2030"
}

### TEST DELETE /api/launches/:id
DELETE http://localhost:8000/api/launches/105